title: Drchanmp's Blog
description: Personal Blog based on Jekyll and GitHub Pages.
social_link: twitter
social_username: drcklinn
github_repo: drchanmp.github.io
github_username: drchanmp
theme_color: blue
remote_theme: internet-de-france/athena
baseurl: /
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: Pages
  - scope:
      path: ''
      type: posts
    values:
      categories: Posts
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - linkedin
theme_colors:
  - light
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
